name: Create issue card in project
on:
  issues:
    types:
      - assigned

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: backend
          column: To do
          repo-token: ${{ secrets.TOKEN }}